# your informations
author:
  name: Shibo Zhang
  description:
  picture: /assets/images/avatar.jpg
  favicon: /assets/images/favicon.png

# site description
description: Thoughts and writings about machine learning.

# site url
url: https://zsb87.github.io/

# site title
title: Shibo Zhang

# site version
version: 1.0.1

# number of posts per page
paginate: 10

# your github username
github_username: zsb87

# set true to include or false to exclude share option
share:
  twitter: true
  facebook: true
  # google_plus: true
  linkedin: true
  # disqus: true

# if share.facebook is true, provide your facebook app id
facebook_app_id: 195303544434918

# # if share.disqus is true, provide your disqus shortname, the api key and the number of comments to display
# disqus_username: bernardopacheco
# disqus_api_key: o2szu05bLNqiXiRvqe2oFvIHYYVR24eVkQiGs5WHcj0VUnvF8GCqD9HQUZErwCe7
# disqus_recent_comments_to_display: 5

# google analytics ID
google_analytics_id: UA-120005293-1

markdown: kramdown
highlighter: rouge
exclude: [ 'README.md', 'src/', 'node_modules', 'package.json', 'Gruntfile.js' ]
excerpt_separator: <!--excerpt_separator-->

# Gems
gems: [jekyll-paginate]